### ISSUE TITLE
lume.array

### ISSUE THREAD

**Issue by buckle2000** [rxi/lume#17]
Why not use `{...}`?

**Comment by rxi** [comment]
`...` represents multiple values in lua, thus the idiom `{ ... }` is an array being built from those multiple values in the same way `{ a, b, c }` would be.

`lume.array()` takes an *iterator* such as that returned by `string.gmatch()`; this iterator is then used with a for loop to build the array. I assume this confusion has stemmed from the source as it uses `...` internally -- this is because of lua's [stateless iterators](https://www.lua.org/pil/7.3.html) which use multiple values.

The following usage example might make things more clear on what the function is for:

```lua
local lume = require("lume")

local text = "Hello world. How are you?"
local iter = text:gmatch("%a+")
local words = lume.array(iter)

for i, word in ipairs(words) do
  print(i, "->", word)
end
```

**Comment by buckle2000** [comment]
Thank you for your explanation!
