### ISSUE TITLE
val^0.5 faster than math.sqrt(val)?

### ISSUE THREAD

**Issue by aubergine10** [rxi/lume#5]
One less function call...

Example:
```
function lume.distance(x1, y1, x2, y2, squared)
  local dx = x1 - x2
  local dy = y1 - y2
  local s = dx * dx + dy * dy
  return squared and s or s^0.5
end
```

**Comment by rxi** [comment]
Ran a little bench mark on the two approaches -- it seems this actually turns out much *slower* than the current implementation on non-JIT lua. I assume the underlying call to C's `pow()` is more expensive than the cost of calling a lua cfunc which then calls C's `sqrt()`.

On LuaJIT there seems to be little difference between either method, per usual!
